SKINS = GLOBAL.STRINGS.SKIN_NAMES
SKINSDESC = GLOBAL.STRINGS.SKIN_DESCRIPTIONS
STRINGS = GLOBAL.STRINGS.NAMES
UI = GLOBAL.STRINGS.UI

STRINGS.IR_CATAPULT = "Catapult"
STRINGS.IR_GENERATOR_BURNABLE = "Stirling Generator"
STRINGS.IR_GENERATOR_BATTERY = "Chemical Battery"

STRINGS.IR_POWERLINE = "Power Post"
STRINGS.IR_LIGHTPOST = "Light Post"

STRINGS.IR_SPOTLIGHT = "Spotlight"