SKINS = GLOBAL.STRINGS.SKIN_NAMES
SKINSDESC = GLOBAL.STRINGS.SKIN_DESCRIPTIONS
STRINGS = GLOBAL.STRINGS.NAMES
UI = GLOBAL.STRINGS.UI

STRINGS.IR_CATAPULT = "Catapult"
STRINGS.IR_GENERATOR_BURNABLE = "Stirling Generator"
STRINGS.IR_GENERATOR_BATTERY = "Chemical Battery"

STRINGS.IR_NODE_POWER = "Power Node"
STRINGS.IR_NODE_POWER_LIGHT = "Light Post"

STRINGS.IR_SPOTLIGHT = "Spotlight"
        
STRINGS.IR_TECH_PROTOTYPER = "Wiring Table"
STRINGS.IR_TECH_PROTOTYPER2 = "Electronics Desk"

STRINGS.IR_HEALING_PAD = "Healing Pad"

STRINGS.IR_REFINERY = "Refinery"
STRINGS.IR_NODE_ITEM = "Item Node"
STRINGS.IR_UPGRADER_ITEMNETWORK = "Item Network Upgrade"