ANNOUNCE = GLOBAL.STRINGS.CHARACTERS.GENERIC
DESCRIBE = GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE
ACTIONFAIL = GLOBAL.STRINGS.CHARACTERS.GENERIC.ACTIONFAIL

local _ICEBOX = DESCRIBE.ICEBOX

DESCRIBE.ICEBOX = 
{
        GENERIC = _ICEBOX,
        OFF = "It needs some electricity."
}